### ISSUE TITLE
Plan for full integration of nested sidebar

### ISSUE THREAD

**Issue by stevector** [pantheon-systems/documentation#9084]
#9047 is adding the nested sidebar element to the certification section of the website and all the decoupled guides. This issue exists to track the follow up work of making all pages within the site fit under an all-encompassing sidebar nav

**Todos (in no particular order)**

- [ ] Identify next subset of page/sections that would especially benefit from a (nested) sidebar nav (like the pages under `source/content/addons/object-cache`)
- [ ] Create some sort of automated report that counts the number of total Docs pages (that aren't specifically excluded) against the total number of pages in the sidebar (that report should reach %100)
- [ ] Audit which pages (like `/sftp`) have redirects away from them on the live domain. (https://pr-9115-documentation.appa.pantheon.site/sftp is accessible but https://docs.pantheon.io/sftp is redirected)
- [ ] Decide which templates and page types need the sidebar. As of these writing, the sidebar in the video template is present but the layout is wrong. And landing pages like https://docs.pantheon.io/develop should perhaps not have the sidebar because the parentage in the sidebar might not fully align with the parentage implied on pages like `/develop`

**Comment by stevector** [comment]
Closed by #9097
